Repository user12986714/SpamSoup, pull requests merged in 2020-06, with the labels that each got.

#3 Use constants instead of magic numbers
  vc/ngram.c
  vc/sbph.c
Labels: refactoring

#6 Minor changes in implementation
  cf/nbc.c
  vc/sbph.c
Labels: refactoring

#8 Simple build script
  build.sh
Labels: enhancement, script

#10 build.sh: Fixed build target location bug
  build.sh
Labels: bug, script

#9 Bare minimum functionalities
  build.sh
  cf/cfutils.c
  cf/cfutils.h
  cf/nbc.c
  vc/bow.c
  vc/ngram.c
  vc/sbph.c
  vc/vcutils.c
  vc/vcutils.h
Labels: to-prod

#11 Implemented script for creating NBC data file
  build.sh
  utils/mknbcdat.sh
Labels: script

#16 Fix Bayes theorem
  build.sh
  cf/cfutils.c
  cf/cfutils.h
  cf/nbc.c
  utils/mknbcdat.sh
  utils/ms.py
Labels: bug

#17 Glueware and bug fixes
  build.sh
  cf/cfutils.c
  cf/cfutils.h
  cf/nbc.c
  utils/config.py
  utils/mknbcdat.sh
  utils/ms.py
Labels: bug, to-prod

#21 ms.py: Handle situations when the user is deleted
  utils/ms.py
Labels: bug

#22 nbc.c: Interpret spam as tokens, not posts
  cf/nbc.c
Labels: enhancement

#23 ms.py: Actually limit amount of connection retries
  utils/ms.py
Labels: bug

#24 build.sh: Copy and enable x for ms.py
  build.sh
Labels: script

#27 config.py: Added version and location config
  utils/config.py
  utils/ms.py
Labels: enhancement

#29 build.sh: Fix path issues for ms.py, stopword.py
  build.sh
Labels: bug, script

#25 Release 0 (Unsure)
  build.sh
  cf/nbc.c
  utils/config.py
  utils/mknbcdat.sh
  utils/ms.py
  utils/stopword.py
  vc/sbph.c
Labels: release, to-prod

#30 Restructure the repository
  build.sh
  src/cf/cfutils.c
  src/cf/cfutils.h
  src/cf/nbc.c
  src/config.json
  src/ms.py
  src/tk/nt.py
  src/tk/stopword.py
  src/vc/bow.c
  src/vc/ngram.c
  src/vc/sbph.c
  src/vc/vcutils.c
  src/vc/vcutils.h
  src/verinfo.json
  utils/config.py
Labels: refactoring

#32 [Bugfix] Fix stopword list; fix json
  src/config.json
  src/ms.py
  src/tk/nt.py
  src/tk/stopword.py
Labels: bug

#33 utils/: Add script for learning from MS database
  utils/README_UTILS
  utils/learn_ms/genline.sh
  utils/learn_ms/joinline.py
  utils/learn_ms/learn.py
  utils/learn_ms/splitline.py
Labels: external

#34 Rearchitect glueware - Don't use the monolithic solution
  build.sh
  src/cf/nbc.c
  src/cfg.json.sample
  src/cfgparse.py
  src/config.json
  src/dataproc.py
  src/glue.py
  src/ml.py
  src/ms.py
  src/msapi.py
  src/msg.py
  src/stopword.py
  src/tk/nt.py
  src/verinfo.json
  src/verinfo.py
  utils/learn_ms/learn.py
Labels: enhancement, refactoring

#35 glue.py: Learn each post only once
  src/glue.py
Labels: bug

#37 Dockerfile
  Dockerfile
  build.sh
Labels: script

#39 Rearchitect glueware for configurable ml routes
  build.sh
  src/cf/cfutils.c
  src/cf/cfutils.h
  src/cf/nbc.c
  src/cfg.json.sample
  src/cfgparse.py
  src/dataproc.py
  src/glue.py
  src/ml.py
  src/msapi.py
  src/msg.py
  src/stopword.py
  src/vc/bow.c
  src/vc/ngram.c
  src/vc/sbph.c
  src/vc/vcutils.c
  src/vc/vcutils.h
  src/verinfo.py
  utils/README_UTILS
  utils/config.py
  utils/learn_ms/genline.sh
  utils/learn_ms/joinline.py
  utils/learn_ms/learn.py
  utils/learn_ms/splitline.py
  utils/ms.py
  utils/stopword.py
Labels: refactoring, to-prod
